name: ci
on:
  workflow_call:
    inputs:
      upload_artifact_name:
        type: string
        required: false
        default: ""

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-node@v4
      - name: Cache node_modules
        id: node_modules_cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node${{ inputs.node_version }}-${{ hashFiles('package-lock.json') }}
      - name: Install deps (npm ci on cache miss)
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload build artifact (optional)
        if: ${{ inputs.upload_artifact_name != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload_artifact_name }}
          path: |
            main.js
            styles.css
            manifest.json
          if-no-files-found: error
          retention-days: 1
