name: tag-release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write   # needed to create releases

jobs:
  ci:
    if: startsWith(github.ref, 'refs/tags/') && github.ref_name matches '^v\d+\.\d+\.\d+.*$'
    uses: ./.github/workflows/ci.yml
    with:
      upload_artifact_name: "dist-${{ github.ref_name }}"

  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: "dist-${{ github.ref_name }}"
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/**
